dist: trusty
sudo: required
language: bash

before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-09/run.sh | bash
# Rename all .example files
- find . -name "*.example" -exec bash -c 'mv "$1" "${1%.example}"' - '{}' \;
# Create ssh-key for appuser
- touch ~/.ssh/appuser && touch ~/.ssh/appuser.pub

install:
# Install ansible and ansible-lint
- sudo pip install --upgrade pip
- sudo pip install ansible ansible-lint
# Install terraform
- wget https://releases.hashicorp.com/terraform/0.11.10/terraform_0.11.10_linux_amd64.zip -t 3
- sudo unzip terraform_0.11.10_linux_amd64.zip -d /usr/local/bin
- export PATH=/usr/local/bin:$PATH
# Install tflint
- wget https://github.com/wata727/tflint/releases/download/v0.7.2/tflint_linux_amd64.zip -t 3
- unzip tflint_linux_amd64.zip
- sudo mkdir -p /usr/local/tflint/bin
- export PATH=/usr/local/tflint/bin:$PATH
- sudo install tflint /usr/local/tflint/bin

script:
# Check packer templates
- find packer -iname '*.json' -not -name variables.json -exec packer validate -var-file=packer/variables.json {} \;
# Check terraform files
- cd terraform/prod && terraform init -backend=false && terraform validate -var-file=terraform.tfvars && tflint
- cd ../stage && terraform init -backend=false && terraform validate -var-file=terraform.tfvars && tflint
# Check ansible playbooks
- cd ../../ansible && ansible-lint playbooks/*.yml --exclude=roles/jdauphant.nginx

notifications:
  slack:
    rooms:
      secure: MGL0+hsP9xBzlP8t2VwclpazisYctk+05KsZbcZiolQJfvIin9rmPO9WtPPUq2K7smSsiRJk72aYuTRAcJUL8/Bagf4mnjFBq9jQ/9DLqyHIFT33Llpt8oLWtb9H36kq2dVfAihp5QmJ5/MRG9RmpM/9TgleTs6gyEzF2SxgS2td2VICL4choHQWjrodoMYwps4nozkh0AHmT330ODVr8OkR9B3NtjhpkdyXHzwksX50RjqvVCPzr3j/7F9TbrVr2VzBqO9PNAhGQFj2GIIvqwfcBy1d909AxsTRU0zbIz5m+ff9Zt1XPxz81b58vEt4gbHtn5oQkcS7jv5WIvtcrvDphEK/Cuku7ae400GkEVQi1uELwzRF1TRDkXBYhltouEyUfQO1MvExboiyxcFA7HvUsz0TOvvDmEyJlwzhpojRhGTIUrH0FAi60CgvugKbh3Bxe95OWKCaPN60ce0bMr/RwF7Zyid+10OBBkeMbqkhW5vw1KzZUyDcD3hgDmqeoSeJoMarwMglS1roTfsGoYbNe9J8gtH+FQvyjuIAUiFD1YKteIs1phCa00JUjN9HdMB65n1hRXPRT4D7TcZPAmvylvWfUOyEgrZRSe0US4/GX6Ml0vk+pQkte9y8zJMGFuSFJD+hiy0j6c3wkTdEDaCxWiJHvVMQimIGc7MTw/A=
